// Options the user could type in
const prompts = [
  ["hi", "hey", "hello", "good morning", "good afternoon"],
  ["how are you", "how is life", "how are things"],
  ["what are you doing", "what is going on", "what is up"],
  ["how old are you"],
  ["who are you", "are you human", "are you bot", "are you human or bot"],
  ["who created you", "who made you"],
  [
    "your name please",
    "your name",
    "may i know your name",
    "what is your name",
    "what call yourself"
  ],

  ["i love you"],
  ["happy", "good", "fun", "wonderful", "fantastic", "cool"],
  ["bad", "bored", "tired"],
  ["help me", "tell me story", "tell me joke"],
  ["ah", "yes", "ok", "okay", "nice"],
  ["bye", "good bye", "goodbye", "see you later"],
  ["what should i eat today"],
  ["bro"],
  ["what", "why", "how", "where", "when"],
  ["no","not sure","maybe","no thanks"],
  [""],
  ["haha","ha","lol","hehe","funny","joke"] 
  [
    "I'm considering divorce and need advice on the legal process."
    ],
  [   
      "Do", "I", "need", "a", "license", "to", "start", "a", "business?",
      "Where", "can", "I", "register", "my", "business?",
      "How", "much", "does", "it", "cost", "to", "register", "a", "business?",
      "Is", "there", "a", "deadline", "for", "business", "registration?",
      "Can", "I", "register", "my", "business", "online?",
      "What", "documents", "are", "required", "for", "business", "registration?",
      "How", "long", "does", "business", "registration", "take?",
      "Can", "I", "register", "my", "business", "as", "a", "sole", "proprietorship?",
      "What", "are", "the", "benefits", "of", "registering", "my", "business?",
      "Do", "I", "need", "to", "register", "my", "business", "name", "separately?",
      "Can", "I", "register", "my", "business", "if", "I'm", "not", "a", "citizen?",
      "What", "are", "the", "tax", "implications", "of", "business", "registration?",
      "Can", "I", "register", "my", "business", "from", "home?",
      "Is", "there", "a", "minimum", "age", "requirement", "for", "business", "registration?",
      "Do", "I", "need", "a", "physical", "address", "to", "register", "my", "business?",
      "What", "type", "of", "business", "structure", "should", "I", "choose", "for", "registration?",
      "Can", "I", "register", "my", "business", "without", "a", "business", "plan?",
      "Is", "there", "financial", "assistance", "available", "for", "business", "registration", "fees?",
      "business", "registration",
      "BUSINESS", "REGISTRATION"
    ],
    [
      "Speeding", "fines?",
      "Speeding", "ticket", "cost?",
      "Speeding", "penalty?",
      "Fine", "for", "overspeeding?",
      "Speeding", "fine?",
      "Speeding", "ticket", "amount?",
      "Consequences", "of", "speeding?",
      "Speeding", "laws?",
      "Speeding", "ticket", "payment?",
      "Speeding", "ticket", "points?",
      "Speeding", "violation?",
      "Speeding", "ticket", "fine?",
      "Speeding", "ticket", "consequences?",
      "Caught", "speeding?",
      "Speeding", "fine", "range?",
      "Speeding", "ticket", "procedure?",
      "Speeding", "fine", "details?",
      "Speeding", "fine", "payment?",
      "Speeding", "ticket", "information?",
      "How", "much", "for", "speeding?",
      "Speeding", "fine", "amount?",
      "Speeding", "ticket", "fine", "range?",
      "Speeding", "ticket", "charges?",
      "what", "will", "be", "the", "cost", "of", "speeding",
      "what", "are", "the", "fine", "for", "speeding",
      "what", "charges", "for", "speeding",
      "speeding",
      "SPEEDING"
  ],
  [
    "Drink", "and", "driving", "consequences?",
    "DUI", "penalties?",
    "Drink", "and", "driving", "fines?",
    "Drinking", "and", "driving", "laws?",
    "Drink", "and", "driving", "charges?",
    "Driving", "under", "the", "influence", "penalties?",
    "DWI", "consequences?",
    "Drink", "driving", "laws", "in", "india?",
    "Consequences", "of", "DUI?",
    "DUI", "fines?",
    "DWI", "laws?",
    "Drinking", "and", "driving", "punishment?",
    "Legal", "limit", "for", "drink?",
    "Alcohol", "limit", "for", "driving?",
    "Is", "Drink", "and", "driving", "legal?",
    "Blood", "alcohol", "limit?",
    "Breathalyzer", "test", "laws", "?",
    "DUI", "checkpoints?",
    "Drink", "and", "driving", "arrest", "consequences?",
    "charges", "under", "drink", "and", "driving",
    "fines", "in", "drink", "and", "driving",
    "drink", "and", "drive",
    "dnd",
    "Drink", "and", "drive",
    "DRINK", "AND", "DRIVE"
  ],
  [
    "Hit", "and", "run", "consequences?",
    "Penalties", "for", "hit", "and", "run?",
    "Hit", "and", "run", "laws?",
    "Hit", "and", "run", "charges?",
    "Consequences", "of", "leaving", "the", "scene", "of", "an", "accident?",
    "Legal", "repercussions", "for", "hit", "and", "run?",
    "Hit", "and", "run", "fines?",
    "Reporting", "a", "hit", "and", "run?",
    "Hit", "and", "run", "punishment?",
    "What", "to", "do", "after", "a", "hit", "and", "run?",
    "Hit", "and", "run", "legal", "process?",
    "Hit", "and", "run", "accident", "consequences?",
    "Hit", "and", "run", "penalties", "in", "[location]?",
    "Hit", "and", "run", "arrest", "consequences?",
    "Hit", "and", "run", "investigation", "process?",
    "Hit", "and", "run", "insurance", "consequences?",
    "Hit", "and", "run", "victim", "compensation?",
    "Hit", "and", "run", "civil", "liabilities?",
    "Hit", "and", "run", "criminal", "charges?",
    "hit", "and", "run", "charges?",
    "what", "are", "the", "charges", "for", "hit", "and", "run.",
    "Hit", "and", "run", "defense", "options?"
  ],
  [
    "No", "license", "consequences?",
    "Penalties", "for", "driving", "without", "a", "license?",
    "Driving", "without", "license", "fines?",
    "Consequences", "of", "driving", "without", "a", "license?",
    "No", "driving", "license", "consequences?",
    "Legal", "repercussions", "for", "driving", "without", "a", "license?",
    "Driving", "without", "license", "penalties?",
    "No", "license", "charges?",
    "What", "happens", "if", "I", "drive", "without", "a", "license?",
    "No", "license", "legal", "implications?",
    "Fines", "for", "driving", "without", "a", "license?",
    "Driving", "without", "a", "license", "punishment?",
    "Driving", "without", "a", "valid", "license", "consequences?",
    "No", "driver's", "license", "fines", "in", "[location]?",
    "Driving", "without", "a", "license", "enforcement", "consequences?",
    "Driving", "without", "a", "license", "legal", "consequences?",
    "Penalties", "for", "no", "license", "while", "driving?",
    "What", "to", "do", "if", "caught", "driving", "without", "a", "license?",
    "Legal", "consequences", "of", "not", "having", "a", "license?",
    "Driving", "without", "a", "license", "penalties", "in", "india?",
    "law", "for", "driving", "without", "a", "license"
  ]
]

// Possible responses, in corresponding order

const replies = [
  ["Hello!", "Hi!", "Hey!", "Hi there!","Howdy"],
  [
    "Fine... how are you?",
    "Pretty well, how are you?",
    "Fantastic, how are you?"
  ],
  [
    "Nothing much",
    "About to go to sleep",
    "Can you guess?",
    "I don't know actually"
  ],
  ["I am infinite"],
  ["I am just a bot", "I am a bot. What are you?"],
  ["The one true God, JavaScript"],
  ["I am nameless", "I don't have a name"],
  ["I love you too", "Me too"],
  ["Have you ever felt bad?", "Glad to hear it"],
  ["Why?", "Why? You shouldn't!", "Try watching TV"],
  ["What about?", "Once upon a time..."],
  ["Tell me a story", "Tell me a joke", "Tell me about yourself"],
  ["Bye", "Goodbye", "See you later"],
  ["Sushi", "Pizza"],
  ["Bro!"],
  ["Great question"],
  ["That's ok","I understand","What do you want to talk about?"],
  ["Please say something :("],
  ["Haha!","Good one!"], 
  ["Consider consulting a family lawyer for divorce proceedings It's advisable to consult with a local divorce attorney to ensure you follow the correct procedure",
    " In some cases a separation agreement may be beneficial before filing for divorce especially if you and your spouse have assets or children to consider It advisable to consult with a divorce attorney to determine if a separation agreement is necessary in your situation",
    "In some cases divorces can be finalized without going to court through methods such as mediation or collaborative divorce"],

  [
      "You", "may", "need", "to", "register", "your", "business", "with", "the", "local", "authorities.",
      "To", "register", "your", "business,", "you", "will", "typically", "need", "to", "follow", "specific", "steps", "outlined", "by", "your", "local", "government", "or", "business", "registration", "authority.", "These", "steps", "may", "include", "selecting", "a", "business", "structure,", "choosing", "a", "business", "name,", "obtaining", "necessary", "licenses", "and", "permits,", "and", "submitting", "required", "documents.", "It's", "advisable", "to", "consult", "with", "your", "local", "Small", "Business", "Administration", "or", "a", "business", "attorney", "for", "guidance", "tailored", "to", "your", "location", "and", "business", "type.",
      "The", "steps", "for", "business", "registration", "can", "vary", "depending", "on", "your", "location", "and", "the", "type", "of", "business", "you're", "starting.", "However,", "common", "steps", "may", "include", "conducting", "market", "research,", "choosing", "a", "business", "structure,", "registering", "your", "business", "name,", "obtaining", "necessary", "licenses", "and", "permits,", "registering", "for", "taxes,", "and", "setting", "up", "business", "banking.", "It's", "recommended", "to", "consult", "with", "your", "local", "Small", "Business", "Administration", "or", "a", "business", "attorney", "to", "ensure", "you", "follow", "the", "correct", "procedure.", "You", "may", "need", "to", "register", "your", "business", "with", "the", "local", "authorities.",
      "The", "need", "for", "a", "business", "license", "depends", "on", "various", "factors", "such", "as", "your", "location,", "business", "type,", "and", "industry", "regulations.", "Some", "businesses", "may", "require", "specific", "licenses", "or", "permits", "to", "operate", "legally.", "It's", "essential", "to", "research", "the", "licensing", "requirements", "in", "your", "area", "and", "consult", "with", "your", "local", "government", "or", "a", "business", "attorney", "to", "determine", "the", "licenses", "you", "need", "for", "your", "business.", "You", "may", "need", "to", "register", "your", "business", "with", "the", "local", "authorities.",
      "The", "cost", "of", "registering", "a", "business", "can", "vary", "depending", "on", "factors", "such", "as", "your", "location,", "business", "structure,", "and", "registration", "fees", "set", "by", "your", "state", "or", "local", "government.", "Common", "expenses", "may", "include", "filing", "fees,", "license", "fees,", "and", "legal", "fees", "if", "you", "choose", "to", "work", "with", "a", "business", "attorney.", "It's", "advisable", "to", "research", "the", "costs", "associated", "with", "business", "registration", "in", "your", "area", "and", "budget", "accordingly.", "You", "may", "need", "to", "register", "your", "business", "with", "the", "local", "authorities.",
      "Many", "jurisdictions", "offer", "online", "registration", "services", "for", "businesses,", "allowing", "you", "to", "complete", "the", "registration", "process", "conveniently", "from", "your", "computer.", "However,", "the", "availability", "of", "online", "registration", "may", "vary", "depending", "on", "your", "location", "and", "the", "specific", "requirements", "of", "your", "business.", "It's", "recommended", "to", "check", "with", "your", "local", "business", "registration", "authority", "or", "visit", "their", "website", "to", "determine", "if", "online", "registration", "is", "an", "option", "for", "your", "business.",
  ],
  [
    "The", "cost", "of", "a", "speeding", "ticket", "can", "vary", "based", "on", "factors", "such", "as", "the", "speed", "limit", "exceeded", "and", "the", "jurisdiction,", "ranging", "from", "2000", "to", "4000.",
    "Penalties", "for", "speeding", "violations", "may", "include", "fines,", "points", "on", "your", "driving", "record,", "and", "potential", "increases", "in", "insurance", "premiums.It", "ranges", "from", "2000", "to", "4000.",
    "The", "fine", "for", "speeding", "depends", "on", "various", "factors,", "such", "as", "the", "speed", "limit,", "the", "extent", "of", "the", "violation,", "and", "the", "local", "regulations.It", "ranges", "from", "2000", "to", "4000.",
    "Speeding", "fines", "vary", "by", "location,", "so", "it's", "essential", "to", "check", "the", "specific", "laws", "and", "regulations", "in", "your", "area", "for", "accurate", "information.It", "ranges", "from", "2000", "to", "4000.",
    "Speeding", "ticket", "amounts", "can", "differ", "based", "on", "factors", "like", "the", "speed", "limit", "exceeded", "and", "any", "additional", "circumstances", "surrounding", "the", "violation.It", "ranges", "from", "2000", "to", "4000.",
    "Consequences", "of", "speeding", "may", "include", "fines,", "points", "on", "your", "license,", "higher", "insurance", "rates,", "and", "potential", "license", "suspension.It", "ranges", "from", "2000", "to", "4000.",
    "Laws", "regarding", "speeding", "vary", "by", "jurisdiction,", "so", "it's", "important", "to", "familiarize", "yourself", "with", "the", "specific", "regulations", "in", "your", "area.It", "ranges", "from", "2000", "to", "4000.",
    "Payment", "for", "a", "speeding", "ticket", "is", "typically", "made", "to", "the", "relevant", "traffic", "authority,", "following", "the", "instructions", "provided", "on", "the", "ticket.It", "ranges", "from", "2000", "to", "4000.",
    "Exceeding", "the", "speed", "limit", "can", "result", "in", "receiving", "a", "speeding", "ticket,", "which", "may", "carry", "fines", "and", "other", "penalties.It", "ranges", "from", "2000", "to", "4000."
  ],
  [
    "Consequences", "of", "drunk", "driving", "may", "include", "fines,", "license", "suspension,", "imprisonment,", "and", "higher", "insurance", "premiums.",
    "Penalties", "for", "DUI", "(Driving", "Under", "the", "Influence)", "can", "vary", "by", "jurisdiction", "but", "may", "include", "fines,", "license", "suspension,", "and", "mandatory", "alcohol", "education", "programs.", "In", "India", "typically", "ranged", "from", "2,000", "to", "10,000", "rupees", "or", "more", "depending", "on", "the", "location", "and", "the", "severity", "of", "the", "offense.",
    "Drink", "driving", "fines", "can", "range", "from", "[amount]", "to", "[amount],", "depending", "on", "factors", "such", "as", "blood", "alcohol", "concentration", "(BAC)", "and", "previous", "offenses.", "In", "India", "typically", "ranged", "from", "2,000", "to", "10,000", "rupees", "or", "more", "depending", "on", "the", "location", "and", "the", "severity", "of", "the", "offense.",
    "Laws", "regarding", "drinking", "and", "driving", "prohibit", "operating", "a", "vehicle", "while", "under", "the", "influence", "of", "alcohol", "or", "drugs,", "with", "penalties", "varying", "by", "location.", "In", "India", "typically", "ranged", "from", "2,000", "to", "10,000", "rupees", "or", "more", "depending", "on", "the", "location", "and", "the", "severity", "of", "the", "offense.",
    "DUI", "charges", "can", "result", "in", "legal", "consequences", "such", "as", "fines,", "license", "suspension,", "and", "potential", "imprisonment,", "depending", "on", "the", "severity", "of", "the", "offense.", "In", "India", "typically", "ranged", "from", "2,000", "to", "10,000", "rupees", "or", "more", "depending", "on", "the", "location", "and", "the", "severity", "of", "the", "offense.",
    "Driving", "under", "the", "influence", "penalties", "may", "include", "fines,", "license", "suspension,", "mandatory", "substance", "abuse", "treatment,", "and", "community", "service.", "In", "India", "typically", "ranged", "from", "2,000", "to", "10,000", "rupees", "or", "more", "depending", "on", "the", "location", "and", "the", "severity", "of", "the", "offense.",
    "DWI", "(Driving", "While", "Intoxicated)", "consequences", "may", "include", "fines,", "license", "revocation,", "and", "even", "imprisonment,", "depending", "on", "the", "circumstances", "and", "jurisdiction.", "In", "India", "typically", "ranged", "from", "2,000", "to", "10,000", "rupees", "or", "more", "depending", "on", "the", "location", "and", "the", "severity", "of", "the", "offense.",
    "Drink", "driving", "laws", "in", "[location]", "dictate", "the", "legal", "blood", "alcohol", "limit", "and", "enforce", "penalties", "for", "violations,", "including", "fines", "and", "license", "suspension.", "In", "India", "typically", "ranged", "from", "2,000", "to", "10,000", "rupees", "or", "more", "depending", "on", "the", "location", "and", "the", "severity", "of", "the", "offense.",
    "Drunk", "driving", "fines", "in", "[location]", "typically", "range", "from", "[amount]", "to", "[amount],", "depending", "on", "factors", "such", "as", "BAC", "level", "and", "previous", "offenses.", "In", "India", "typically", "ranged", "from", "2,000", "to", "10,000", "rupees", "or", "more", "depending", "on", "the", "location", "and", "the", "severity", "of", "the", "offense.",
    "Consequences", "of", "DUI", "convictions", "can", "have", "long-term", "effects", "on", "one's", "record,", "employment", "prospects,", "and", "personal", "life,", "in", "addition", "to", "legal", "penalties."
  ],
  [
    "Consequences", "of", "hit", "and", "run", "may", "include", "criminal", "charges,", "fines,", "license", "suspension,", "and", "potential", "imprisonment.",
    "Penalties", "for", "hit", "and", "run", "can", "vary", "by", "jurisdiction", "but", "often", "include", "severe", "legal", "consequences,", "such", "as", "fines", "and", "imprisonment.",
    "Hit", "and", "run", "laws", "mandate", "that", "drivers", "involved", "in", "accidents", "must", "stop,", "exchange", "information,", "and", "render", "aid", "to", "injured", "parties.",
    "Hit", "and", "run", "charges", "can", "result", "in", "legal", "ramifications,", "including", "criminal", "prosecution", "and", "civil", "liability", "for", "damages.",
    "Consequences", "of", "leaving", "the", "scene", "of", "an", "accident", "may", "include", "criminal", "charges,", "fines,", "and", "civil", "lawsuits", "for", "damages.",
    "Legal", "repercussions", "for", "hit", "and", "run", "offenses", "may", "involve", "criminal", "charges,", "substantial", "fines,", "and", "potential", "incarceration.",
    "Hit", "and", "run", "fines", "can", "be", "significant,", "and", "perpetrators", "may", "also", "face", "civil", "lawsuits", "for", "damages", "caused", "by", "their", "actions.",
    "Reporting", "a", "hit", "and", "run", "is", "crucial", "for", "initiating", "an", "investigation", "and", "holding", "responsible", "parties", "accountable", "for", "their", "actions.",
    "Hit", "and", "run", "punishment", "may", "include", "criminal", "penalties", "such", "as", "fines,", "probation,", "community", "service,", "and", "jail", "time.",
    "After", "a", "hit", "and", "run,", "it's", "essential", "to", "report", "the", "incident", "to", "law", "enforcement", "and", "seek", "legal", "assistance", "to", "protect", "your", "rights.",
    "The", "hit", "and", "run", "legal", "process", "involves", "investigation", "by", "law", "enforcement,", "potential", "criminal", "charges,", "and", "civil", "litigation", "for", "damages.",
    "Hit", "and", "run", "accident", "consequences", "can", "have", "long-lasting", "effects", "on", "victims,", "including", "physical", "injuries,", "emotional", "trauma,", "and", "financial", "hardships.",
    "Hit", "and", "run", "penalties", "in", "[location]", "may", "vary,", "but", "typically", "include", "severe", "legal", "repercussions", "for", "offenders.",
    "Hit", "and", "run", "arrest", "consequences", "can", "include", "criminal", "charges,", "potential", "imprisonment,", "and", "a", "permanent", "criminal", "record.",
    "The", "hit", "and", "run", "investigation", "process", "involves", "gathering", "evidence,", "identifying", "suspects,", "and", "pursuing", "criminal", "charges", "against", "responsible", "parties.",
    "Hit", "and", "run", "insurance", "consequences", "may", "involve", "increased", "premiums,", "policy", "cancellation,", "or", "denial", "of", "coverage", "for", "the", "offender.",
    "Hit", "and", "run", "victim", "compensation", "may", "be", "available", "through", "civil", "lawsuits", "against", "the", "responsible", "party", "for", "damages", "suffered.",
    "Hit", "and", "run", "civil", "liabilities", "may", "include", "financial", "responsibility", "for", "property", "damage,", "medical", "expenses,", "and", "other", "losses", "incurred", "by", "victims.",
    "Hit", "and", "run", "criminal", "charges", "may", "result", "in", "severe", "penalties,", "including", "fines,", "probation,", "and", "imprisonment.",
    "Hit", "and", "run", "defense", "options", "may", "include", "legal", "representation,", "negotiation", "with", "prosecutors,", "and", "presenting", "evidence", "to", "challenge", "charges.",
    "The", "fine", "for", "a", "hit", "and", "run", "offense", "in", "India", "can", "vary,", "but", "it", "may", "result", "in", "a", "significant", "penalty,", "imprisonment,", "or", "both,", "depending", "on", "the", "severity", "of", "the", "incident", "and", "the", "specific", "legal", "provisions", "in", "place.",
    "drivers", "who", "cause", "a", "serious", "road", "accident", "by", "negligent", "driving", "and", "run", "away", "without", "informing", "the", "police", "or", "any", "official", "from", "the", "administration", "can", "face", "punishment", "of", "up", "to", "10", "years", "and", "a", "fine", "of", "Rs", "7", "lakh."
  ],
  [
    "Consequences of", "driving", "without", "a", "license", "may", "include", "fines,", "penalties,", "and", "potential", "legal", "action", "by", "authorities.",
    "Fines", "for", "driving", "without", "a", "license", "can", "vary", "by", "location", "but", "may", "range", "₹5000.",
    "Penalties", "for", "driving", "without", "a", "license", "can", "include", "fines,", "vehicle", "impoundment,", "and", "suspension", "of", "driving", "privileges.",
    "Fines", "for", "driving", "without", "a", "license", "can", "vary", "by", "location", "but", "may", "range", "₹5000.",
    "Fines", "for", "driving", "without", "a", "license", "can", "vary", "by", "location", "but", "may", "range", "₹5000.",
    "Driving", "without", "a", "license", "can", "result", "in", "legal", "repercussions,", "including", "fines", "and", "potential", "suspension", "of", "driving", "privileges.",
    "Fines", "for", "driving", "without", "a", "license", "can", "vary", "by", "location", "but", "may", "range", "₹5000.",
    "Legal", "repercussions", "for", "driving", "without", "a", "license", "may", "involve", "fines", "and", "enforcement", "actions", "by", "authorities.",
    "Fines", "for", "driving", "without", "a", "license", "can", "vary", "by", "location", "but", "may", "range", "₹5000.",
    "Driving", "without", "license", "penalties?",
    "No", "license", "charges?",
    "What", "happens", "if", "I", "drive", "without", "a", "license?",
    "No", "license", "legal", "implications?",
    "Fines", "for", "driving", "without", "a", "license", "can", "vary", "by", "location", "but", "may", "range", "₹5000.",
    "Driving", "without", "a", "license", "punishment?",
    "Driving", "without", "a", "valid", "license", "consequences?",
    "No", "driver's", "license", "fines", "in", "[location]?",
    "Driving", "without", "a", "license", "enforcement", "consequences?",
    "Driving", "without", "a", "license", "legal", "consequences?",
    "Penalties", "for", "no", "license", "while", "driving?",
    "What", "to", "do", "if", "caught", "driving", "without", "a", "license?",
    "Legal", "consequences", "of", "not", "having", "a", "license?",
    "Driving", "without", "a", "license", "penalties", "in", "india?",
    "law", "for", "driving", "without", "a", "license"
  ]
]

// Random for any other user input

const alternative = [
  "Same",
  "Go on...",
  "Bro...",
  "Try again",
  "I'm listening...",
  "I don't understand :/"
]

// Whatever else you want :)

const coronavirus = ["Please stay home", "Wear a mask", "Fortunately, I don't have COVID", "These are uncertain times"]